package colombianleaguesoccer;

import com.sun.jdi.connect.spi.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

public class Main extends javax.swing.JFrame {

    
    List<Team> teams = new ArrayList<>();
    League league = new League();
    SimulateJourney simulateJourneyForm;
    TableRowSorter<ModelTeamsTable> tableRowSorter = new TableRowSorter<>();

    
    
    public SimulateJourney getSimulateJourneyForm() {
        return simulateJourneyForm;
    }

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        btnWinner.setVisible(false);
        initObjects();
        this.simulateJourneyForm = new SimulateJourney();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimulate = new javax.swing.JButton();
        btnWinner = new javax.swing.JButton();
        btnRestart = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTeams = new javax.swing.JTable();
        lblTitleLeague = new javax.swing.JLabel();
        lblCreators = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(480, 270));
        setResizable(false);

        btnSimulate.setText("Enter a Journey");
        btnSimulate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulateActionPerformed(evt);
            }
        });

        btnWinner.setText("SHOW THE WINNER");
        btnWinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWinnerActionPerformed(evt);
            }
        });

        btnRestart.setText("Restart the League");
        btnRestart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        btnClose.setText("❌");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        tblTeams.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblTeams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTeams.setAlignmentX(1.0F);
        jScrollPane2.setViewportView(tblTeams);

        lblTitleLeague.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        lblTitleLeague.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleLeague.setText("COLOMBIAN SOCCER LEAGUE");

        lblCreators.setFont(new java.awt.Font("Open Sans ExtraBold", 2, 20)); // NOI18N
        lblCreators.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreators.setText("CREATED BY: ANA GRANADA & JESUS TORRES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitleLeague, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnSimulate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(btnWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCreators, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitleLeague, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimulate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(lblCreators, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulateActionPerformed
        if (league.isFinalized()) {
            btnWinner.setVisible(true);
            JOptionPane.showMessageDialog(null, "THE LEAGUE WAS FINALICED!");
            return;
        }
        if (this.getSimulateJourneyForm() != null && !this.getSimulateJourneyForm().isVisible()) {
            this.getSimulateJourneyForm().setJourney(league.getActualJourney());
            this.getSimulateJourneyForm().setLeague(league);
            this.getSimulateJourneyForm().setMainFrame(this);
            this.getSimulateJourneyForm().setJourneyData();
            this.getSimulateJourneyForm().setLocation(this.getLocation().x, this.getLocation().y);
            this.getSimulateJourneyForm().setVisible(true);
        }

    }//GEN-LAST:event_btnSimulateActionPerformed

    private void btnWinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWinnerActionPerformed
        JOptionPane.showMessageDialog(null, "THE WINNER IS: " + league.getTeams().get(0).getName());
    }//GEN-LAST:event_btnWinnerActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        btnWinner.setVisible(false);
        league.initTeams();
        league.initJourneys();
        initObjects();
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void initObjects() {

        teams = league.getTeams();
        ModelTeamsTable model = new ModelTeamsTable(this.teams);
        tableRowSorter = new TableRowSorter<>(model);
        tblTeams.setRowSorter(tableRowSorter);
        tblTeams.setModel(model);
        tableRowSorter.setComparator(0, (o1, o2) -> Integer.compare((Integer) o2, (Integer) o1));
        tableRowSorter.setComparator(2, (o1, o2) -> Integer.compare((Integer) o2, (Integer) o1));
        tableRowSorter.setComparator(3, (o1, o2) -> Integer.compare((Integer) o2, (Integer) o1));
        tableRowSorter.setComparator(4, (o1, o2) -> Integer.compare((Integer) o2, (Integer) o1));
        tableRowSorter.setComparator(5, (o1, o2) -> Integer.compare((Integer) o2, (Integer) o1));
        tableRowSorter.setComparator(6, (o1, o2) -> Integer.compare((Integer) o2, (Integer) o1));
        tableRowSorter.setComparator(7, (o1, o2) -> Integer.compare((Integer) o2, (Integer) o1));
        tableRowSorter.setComparator(8, (o1, o2) -> Integer.compare((Integer) o2, (Integer) o1));
        tblTeams.getColumnModel().getColumn(1).setMinWidth(130);
        tblTeams.getColumnModel().getColumn(0).setMaxWidth(60);
        tblTeams.getColumnModel().getColumn(8).setMaxWidth(60);
        tblTeams.getTableHeader().setReorderingAllowed(false);
        tblTeams.getTableHeader().setResizingAllowed(false);
        
        if (league.isFinalized()) {
            btnWinner.setVisible(true);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnSimulate;
    private javax.swing.JButton btnWinner;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCreators;
    private javax.swing.JLabel lblTitleLeague;
    private javax.swing.JTable tblTeams;
    // End of variables declaration//GEN-END:variables
}
